configuration: Release

branches:
  only:
    - v1.0

image:
  - Visual Studio 2017

install: 
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

before_build: 
  # Updates the version number in the .vsixmanifest and updates the AppVeyor build number to match
  # - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  - cmd: nuget restore HighlightCommentTags.sln
  
build:
  - HighlightCommentTags.sln

#build_script:
#  cmd: >-
#    msbuild /m /r /clp:v=m HighlightCommentTags.sln /bl /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    
    
#artifacts:
#  path: msbuild.binlog
# name: MSBuild Log

#on_failure:
#  appveyor PushArtifact msbuild.binlog
