//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighlightCommentTags.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HighlightCommentTags.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set foreground color for DEBUG tags..
        /// </summary>
        public static string DebugTagColorTip {
            get {
                return ResourceManager.GetString("DebugTagColorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Tag.
        /// </summary>
        public static string DebugTagTitle {
            get {
                return ResourceManager.GetString("DebugTagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable tags higlighting.
        /// </summary>
        public static string EnableHighlightingCheckBoxTitle {
            get {
                return ResourceManager.GetString("EnableHighlightingCheckBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable all tags highliting in the C/C++ sources.
        /// </summary>
        public static string EnableHiglightingCheckBoxTip {
            get {
                return ResourceManager.GetString("EnableHiglightingCheckBoxTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set foreground color for FIXED tags..
        /// </summary>
        public static string FixedTagColorTip {
            get {
                return ResourceManager.GetString("FixedTagColorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Tag.
        /// </summary>
        public static string FixedTagTitle {
            get {
                return ResourceManager.GetString("FixedTagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set foreground color for FIXME tags..
        /// </summary>
        public static string FixmeTagColorTip {
            get {
                return ResourceManager.GetString("FixmeTagColorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixme Tag.
        /// </summary>
        public static string FixmeTagTitle {
            get {
                return ResourceManager.GetString("FixmeTagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set foreground color for NOTE tags..
        /// </summary>
        public static string NoteTagColorTip {
            get {
                return ResourceManager.GetString("NoteTagColorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Tag.
        /// </summary>
        public static string NoteTagTitle {
            get {
                return ResourceManager.GetString("NoteTagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changes will applied after restart of the Visual Studio.
        /// </summary>
        public static string RequestRestartMessage {
            get {
                return ResourceManager.GetString("RequestRestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to defaults.
        /// </summary>
        public static string ResetButtonContent {
            get {
                return ResourceManager.GetString("ResetButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset colors to defaults values.
        /// </summary>
        public static string ResetButtonTip {
            get {
                return ResourceManager.GetString("ResetButtonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to reset all color settings to their defaults?.
        /// </summary>
        public static string ResetToDefaultsMessage {
            get {
                return ResourceManager.GetString("ResetToDefaultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set foreground color for TODO tags..
        /// </summary>
        public static string TodoTagColorTip {
            get {
                return ResourceManager.GetString("TodoTagColorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo Tag.
        /// </summary>
        public static string TodoTagTitle {
            get {
                return ResourceManager.GetString("TodoTagTitle", resourceCulture);
            }
        }
    }
}
