//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighlightCommentTags.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 128")]
        public global::System.Drawing.Color TodoForeground {
            get {
                return ((global::System.Drawing.Color)(this["TodoForeground"]));
            }
            set {
                this["TodoForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 128")]
        public global::System.Drawing.Color NoteForeground {
            get {
                return ((global::System.Drawing.Color)(this["NoteForeground"]));
            }
            set {
                this["NoteForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color DebugForeground {
            get {
                return ((global::System.Drawing.Color)(this["DebugForeground"]));
            }
            set {
                this["DebugForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 192")]
        public global::System.Drawing.Color FixmeForeground {
            get {
                return ((global::System.Drawing.Color)(this["FixmeForeground"]));
            }
            set {
                this["FixmeForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 128, 255")]
        public global::System.Drawing.Color FixedForeground {
            get {
                return ((global::System.Drawing.Color)(this["FixedForeground"]));
            }
            set {
                this["FixedForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableTagsHighlighting {
            get {
                return ((bool)(this["EnableTagsHighlighting"]));
            }
            set {
                this["EnableTagsHighlighting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double TagsBackgroundOpacity {
            get {
                return ((double)(this["TagsBackgroundOpacity"]));
            }
            set {
                this["TagsBackgroundOpacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseTagBackground {
            get {
                return ((bool)(this["UseTagBackground"]));
            }
            set {
                this["UseTagBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 128, 128")]
        public global::System.Drawing.Color DefaultTodoForeground {
            get {
                return ((global::System.Drawing.Color)(this["DefaultTodoForeground"]));
            }
            set {
                this["DefaultTodoForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 128")]
        public global::System.Drawing.Color DefaultNoteForeground {
            get {
                return ((global::System.Drawing.Color)(this["DefaultNoteForeground"]));
            }
            set {
                this["DefaultNoteForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color DefaultDebugForeground {
            get {
                return ((global::System.Drawing.Color)(this["DefaultDebugForeground"]));
            }
            set {
                this["DefaultDebugForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 192")]
        public global::System.Drawing.Color DefaultFixmeForeground {
            get {
                return ((global::System.Drawing.Color)(this["DefaultFixmeForeground"]));
            }
            set {
                this["DefaultFixmeForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 128, 255")]
        public global::System.Drawing.Color DefaultFixedForeground {
            get {
                return ((global::System.Drawing.Color)(this["DefaultFixedForeground"]));
            }
            set {
                this["DefaultFixedForeground"] = value;
            }
        }
    }
}
